# Generated by Django 6.0.2 on 2026-02-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('regular', 'Регулярное ТО'), ('brakes', 'Тормозная система'), ('chassis', 'Ходовая и рулевое'), ('extra', 'Дополнительные работы'), ('plan', 'План обслуживания')], max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_text', models.CharField(blank=True, max_length=255)),
                ('forecast_text', models.CharField(blank=True, max_length=255)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('repeatability', models.CharField(blank=True, max_length=255)),
                ('plan_period', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_card_entries', to='cars.car')),
            ],
            options={
                'ordering': ('section', '-service_date', '-id'),
            },
        ),
    ]
