# Generated by Django 6.0.2 on 2026-02-18 18:26

import datetime

from django.db import migrations


def seed_service_card_entries(apps, schema_editor):
    User = apps.get_model("users", "User")
    Car = apps.get_model("cars", "Car")
    ServiceCardEntry = apps.get_model("service", "ServiceCardEntry")

    user = User.objects.filter(username="MaximVolkov").first()
    if not user:
        return

    car = Car.objects.filter(owner=user, brand__iexact="Volkswagen", model__icontains="Tiguan").first()
    if not car:
        return

    if ServiceCardEntry.objects.filter(car=car).exists():
        return

    entries = [
        {
            "section": "regular",
            "item_name": "Масло ДВС 5W-40",
            "service_date": datetime.date(2026, 1, 13),
            "mileage": 165930,
            "interval_text": "6-8 мес",
            "forecast_text": "сент-нояб 2026",
        },
        {
            "section": "regular",
            "item_name": "Масляный фильтр",
            "service_date": datetime.date(2026, 1, 13),
            "mileage": 165930,
            "interval_text": "с маслом",
            "forecast_text": "сент-нояб 2026",
        },
        {
            "section": "regular",
            "item_name": "Воздушный фильтр",
            "service_date": datetime.date(2026, 1, 13),
            "mileage": 165930,
            "interval_text": "1 год",
            "forecast_text": "январь 2027",
        },
        {
            "section": "regular",
            "item_name": "Салонный фильтр",
            "service_date": datetime.date(2026, 1, 13),
            "mileage": 165930,
            "interval_text": "1 год",
            "forecast_text": "январь 2027",
        },
        {
            "section": "regular",
            "item_name": "Свечи зажигания NGK",
            "service_date": datetime.date(2025, 6, 30),
            "interval_text": "30-40 тыс км",
            "forecast_text": "2027-2028",
        },
        {
            "section": "regular",
            "item_name": "Масло КПП",
            "service_date": datetime.date(2024, 3, 2),
            "interval_text": "~60 тыс км",
            "forecast_text": "2027-2028",
        },
        {
            "section": "regular",
            "item_name": "Фильтр КПП",
            "service_date": datetime.date(2024, 3, 2),
            "interval_text": "вместе с маслом КПП",
            "forecast_text": "2027-2028",
        },
        {
            "section": "regular",
            "item_name": "Тормозная жидкость DOT4",
            "service_date": datetime.date(2026, 1, 13),
            "mileage": 165930,
            "interval_text": "2 года",
            "forecast_text": "январь 2028",
        },
        {
            "section": "brakes",
            "item_name": "Передние тормозные диски ATE",
            "service_date": datetime.date(2026, 1, 13),
            "interval_text": "50-70 тыс км",
            "forecast_text": "2028-2029",
        },
        {
            "section": "brakes",
            "item_name": "Передние колодки ATE",
            "service_date": datetime.date(2026, 1, 13),
            "interval_text": "30-40 тыс км",
            "forecast_text": "2027",
        },
        {
            "section": "brakes",
            "item_name": "Задние тормозные диски TRW",
            "service_date": datetime.date(2025, 6, 30),
            "interval_text": "60-80 тыс км",
            "forecast_text": "2028-2029",
        },
        {
            "section": "brakes",
            "item_name": "Задние колодки ATE",
            "service_date": datetime.date(2025, 6, 30),
            "interval_text": "35-45 тыс км",
            "forecast_text": "2027",
        },
        {
            "section": "brakes",
            "item_name": "Ремкомплект переднего суппорта",
            "service_date": datetime.date(2026, 1, 13),
            "interval_text": "разово",
            "forecast_text": "-",
        },
        {
            "section": "chassis",
            "item_name": "Шаровая опора Lemforder",
            "service_date": datetime.date(2024, 7, 1),
            "details": "замена",
            "repeatability": "разово",
        },
        {
            "section": "chassis",
            "item_name": "Ремонт рулевой рейки",
            "service_date": datetime.date(2026, 1, 13),
            "details": "капитальный ремонт",
            "repeatability": "разово",
        },
        {
            "section": "chassis",
            "item_name": "Ремонт переднего суппорта",
            "service_date": datetime.date(2026, 1, 13),
            "details": "восстановление",
            "repeatability": "разово",
        },
        {
            "section": "extra",
            "item_name": "Замена ремня ГРМ",
            "service_date": datetime.date(2023, 5, 1),
        },
        {
            "section": "extra",
            "item_name": "Чистка впуска",
            "service_date": datetime.date(2023, 5, 1),
        },
        {
            "section": "extra",
            "item_name": "Мойка радиаторов",
            "service_date": datetime.date(2023, 5, 1),
        },
        {
            "section": "extra",
            "item_name": "Чистка форсунок",
            "service_date": datetime.date(2023, 5, 1),
        },
        {
            "section": "extra",
            "item_name": "Замена замка (оригинал)",
            "service_date": datetime.date(2024, 7, 1),
        },
        {
            "section": "plan",
            "plan_period": "2026 (осень)",
            "item_name": "Масло + фильтр",
        },
        {
            "section": "plan",
            "plan_period": "2026 (осень)",
            "item_name": "Пробка поддона",
        },
        {
            "section": "plan",
            "plan_period": "2027",
            "item_name": "Передние/задние колодки",
        },
        {
            "section": "plan",
            "plan_period": "2027",
            "item_name": "Свечи (по пробегу)",
        },
        {
            "section": "plan",
            "plan_period": "2027",
            "item_name": "Фильтры",
        },
        {
            "section": "plan",
            "plan_period": "2028",
            "item_name": "Тормозная жидкость",
        },
        {
            "section": "plan",
            "plan_period": "2028",
            "item_name": "Масло КПП (если пробег позволит)",
        },
        {
            "section": "plan",
            "plan_period": "2028",
            "item_name": "Контроль тормозных дисков",
        },
    ]

    ServiceCardEntry.objects.bulk_create(
        [ServiceCardEntry(car=car, **entry_data) for entry_data in entries]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("cars", "0002_initial"),
        ("service", "0002_servicecardentry"),
    ]

    operations = [
        migrations.RunPython(seed_service_card_entries, migrations.RunPython.noop),
    ]
