# Generated by Django 6.0.2 on 2026-02-18 18:58

from django.db import migrations, models


def set_element_type_for_existing_entries(apps, schema_editor):
    ServiceCardEntry = apps.get_model("service", "ServiceCardEntry")
    ServiceCardEntry.objects.filter(section__in=["chassis", "extra"]).update(element_type="work")


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_seed_service_card_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecardentry',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicecardentry',
            name='element_type',
            field=models.CharField(choices=[('consumable', 'Расходник ТО'), ('work', 'Работа')], default='consumable', max_length=20),
        ),
        migrations.RunPython(set_element_type_for_existing_entries, migrations.RunPython.noop),
    ]
