# Generated by Django 6.0.2 on 2026-02-18 19:35

from django.db import migrations


ITEM_NAME_ALIASES = {
    "Масло ДВС": "Масло ДВС 5W-40",
    "Фильтр масляный": "Масляный фильтр",
    "Тормозная жидкость": "Тормозная жидкость DOT4",
    "Передние тормозные колодки": "Передние колодки",
    "Задние тормозные колодки": "Задние колодки",
    "Шаровая": "Шаровая опора",
}

CONSUMABLE_ITEMS = {
    "Тормозная жидкость DOT4",
    "Салонный фильтр",
    "Воздушный фильтр",
    "Масляный фильтр",
    "Масло ДВС 5W-40",
    "Свечи зажигания",
    "Фильтр КПП",
    "Масло КПП",
    "Передние колодки",
    "Передние тормозные диски",
    "Задние колодки",
    "Задние тормозные диски",
}

WORK_ITEMS = {
    "Ремонт рулевой рейки",
    "Мойка радиаторов",
    "Чистка форсунок",
    "Замена ремня ГРМ",
    "Чистка впуска",
    "Шаровая опора",
    "Замок оригинал",
    "Ремкомплект суппорта",
}

ITEM_TO_SECTION = {
    "Тормозная жидкость DOT4": "regular",
    "Салонный фильтр": "regular",
    "Воздушный фильтр": "regular",
    "Масляный фильтр": "regular",
    "Масло ДВС 5W-40": "regular",
    "Свечи зажигания": "regular",
    "Фильтр КПП": "regular",
    "Масло КПП": "regular",
    "Передние колодки": "brakes",
    "Передние тормозные диски": "brakes",
    "Задние колодки": "brakes",
    "Задние тормозные диски": "brakes",
    "Ремкомплект суппорта": "brakes",
    "Ремонт рулевой рейки": "chassis",
    "Шаровая опора": "chassis",
    "Мойка радиаторов": "extra",
    "Чистка форсунок": "extra",
    "Замена ремня ГРМ": "extra",
    "Чистка впуска": "extra",
    "Замок оригинал": "extra",
}


def normalize_item_names(apps, schema_editor):
    ServiceCardEntry = apps.get_model("service", "ServiceCardEntry")

    for old_name, new_name in ITEM_NAME_ALIASES.items():
        ServiceCardEntry.objects.filter(item_name=old_name).update(item_name=new_name)

    for item_name, section in ITEM_TO_SECTION.items():
        ServiceCardEntry.objects.filter(item_name=item_name).exclude(section="plan").update(section=section)

    ServiceCardEntry.objects.filter(item_name__in=CONSUMABLE_ITEMS).update(element_type="consumable")
    ServiceCardEntry.objects.filter(item_name__in=WORK_ITEMS).update(element_type="work")


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_servicecardentry_cost_servicecardentry_element_type"),
    ]

    operations = [
        migrations.RunPython(normalize_item_names, migrations.RunPython.noop),
    ]
