# Generated by Django 6.0.2 on 2026-03-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
        ('service', '0005_normalize_item_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('consumable', 'Расходник ТО'), ('work', 'Работа')], max_length=20)),
                ('section', models.CharField(choices=[('regular', 'Регулярное ТО'), ('brakes', 'Тормозная система'), ('chassis', 'Ходовая и рулевое'), ('extra', 'Дополнительные работы'), ('plan', 'План обслуживания')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_service_items', to='cars.car')),
            ],
            options={
                'ordering': ('element_type', 'name'),
                'unique_together': {('car', 'element_type', 'name')},
            },
        ),
    ]
